(lang dune 3.6)

(name bytream)

(generate_opam_files true)

(source
 (github dx3mod/bytream))

(authors "Mikhail Lopatin <dx3mod@bk.ru>")

(maintainers "Mikhail Lopatin <dx3mod@bk.ru>")

(license MIT)

; (documentation https://url/to/documentation)

(package
 (name bytream)
 (synopsis "A streaming bytes and crunching them library")
 (description "A longer description")
 (depends ocaml)
 (tags ()))
